-- TO CREATE DATABASE
CREATE DATABASE APTECH;

-- TO USE DATABASE
USE APTECH;

-- TO CREATE TABLE 
CREATE TABLE MARKSHEET (
ROLL_NUMBER INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
STUDENTS_NAME VARCHAR(250),
PASSING_YEAR INT,
EXAMINATION VARCHAR(250),
PERCENTAGE INT
);

-- TO DISPLAY THE TABLE
SELECT * FROM MARKSHEET;

-- TO INSERT VALUES INTO THE TABLE
INSERT INTO MARKSHEET VALUES (311000, "Asad", 2021, "ANNUAL", 87);
INSERT INTO MARKSHEET VALUES (311001, "Sarah", 2022, "ANNUAL", 84);
INSERT INTO MARKSHEET VALUES (311002, "Abdullah", 2020, "ANNUAL", 67);
INSERT INTO MARKSHEET VALUES (NULL, "Basit", 2021, "ANNUAL", 75);
INSERT INTO MARKSHEET VALUES (NULL, "Ayesha", 2018, "ANNUAL", 68);
INSERT INTO MARKSHEET VALUES (NULL, "Laiba", 2019, "ANNUAL", 55);
INSERT INTO MARKSHEET VALUES (NULL, "Affan", 2019, "ANNUAL", 35);
INSERT INTO MARKSHEET VALUES (NULL, "Hassan", 2020, "SUPPLY", 81);
INSERT INTO MARKSHEET VALUES (NULL, "Umar", 2018, "ANNUAL", 49);
INSERT INTO MARKSHEET VALUES (NULL, "Saad", 2022, "ANNUAL", 45);
INSERT INTO MARKSHEET VALUES (NULL, "Zubair", 2022, "ANNUAL", 23);
INSERT INTO MARKSHEET VALUES (NULL, "Haris", 2021, "ANNUAL", 95);
INSERT INTO MARKSHEET VALUES (NULL, "Uzma", 2019, "ANNUAL", 63);

-- TO PERFORM CASE STATEMENT 
CREATE TABLE MatricResult AS
SELECT STUDENTS_NAME, PERCENTAGE,
    CASE
        WHEN PERCENTAGE >= 80 THEN "A+"
        WHEN PERCENTAGE >= 70 AND PERCENTAGE <= 79 THEN "A"
        WHEN PERCENTAGE >= 60 AND PERCENTAGE <= 69 THEN "B"
        WHEN PERCENTAGE >= 50 AND PERCENTAGE <= 59 THEN "C"
        WHEN PERCENTAGE >= 40 AND PERCENTAGE <= 49 THEN "D"
        ELSE "FAIL"
    END AS GRADE
FROM MARKSHEET;

SELECT * FROM MatricResult;

CREATE TABLE Matric_Result (
StudentsName VARCHAR(250),
PERCENTAGE INT,
Grade VARCHAR(20)
);

INSERT INTO Matric_Result (StudentsName, PERCENTAGE, Grade)
SELECT STUDENTS_NAME, PERCENTAGE,
    CASE
        WHEN PERCENTAGE >= 80 THEN "A+"
        WHEN PERCENTAGE >= 70 AND PERCENTAGE <= 79 THEN "A"
        WHEN PERCENTAGE >= 60 AND PERCENTAGE <= 69 THEN "B"
        WHEN PERCENTAGE >= 50 AND PERCENTAGE <= 59 THEN "C"
        WHEN PERCENTAGE >= 40 AND PERCENTAGE <= 49 THEN "D"
        ELSE "FAIL"
    END AS GRADE
FROM MARKSHEET;

SELECT * FROM Matric_Result;

